In [2]:
#numpy
import numpy

arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [14]:
import numpy as anu  #creating numpy array   
x=anu.array([1,2,4,5,6,7])
print(x)

[1 2 4 5 6 7]


In [7]:
a=[1,2,3,4]
print(type(a))


<class 'list'>


In [8]:
x=np.array([1,2,3,4])   
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
# [1,2,3]   # 1 dim
# [[1,2,3],[4,5,6]]   2 dim
# [[[1,2,3],[4,5,6],[3,4,5]]]  3 dim

In [11]:
import numpy as np

x=np.array([1,2,3])
print(x)
print(x.ndim)   #ndim

[1 2 3]
1


In [13]:
x=np.array([[1,2,3],[3,4,5]])
print(x)
print(x.ndim) 

# # 1 2 3  row
# # 3 4 5  row

# 1
# 3  column

[[1 2 3]
 [3 4 5]]
2


In [14]:
# create 1 array 23,45,67  print dim??
x=np.array([23,45,67])
print(x)
print(x.ndim)

[23 45 67]
1


In [15]:
#[[23,34,45],[45,67,89]]
x=np.array([[23,34,45],[45,67,89]])
print(x)
print(x.ndim)

[[23 34 45]
 [45 67 89]]
2


In [16]:
x=np.array([[[23,34,45],[45,67,89]]])
print(x)
print(x.ndim)

[[[23 34 45]
  [45 67 89]]]
3


In [25]:
import numpy as np
y=np.array([1,2,3,4,5,6,7],ndmin=5)
print(y)
print(y.ndim)

[[[[[1 2 3 4 5 6 7]]]]]
5


In [28]:
#access
arr=np.array([1,2,3,4,5])  #0=1 1=2 2=3 3=4 4=5
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])


1
2
3
4
5


In [31]:
print(arr[0:3])  #012   
print(arr[0]+arr[1])  #1+2
print(arr[4]-arr[3])  #5-4 =1

[1 2 3]
3
1


In [36]:
arr=np.array([[1,2,3],[4,5,6]])  #-=0=[1,2,3]   1=[4,5,6]
print(arr[0,1])   # [rows,colums]   #0=1 1=2 2=3

2


In [39]:
#[[23,45,67],[34,145,67],[67,89,34]]

# 0=[23,45,67]   #0=23 1=45 2=67
#1=[34,145,67]   #0=34 1=145 2=67
#2=[67,89,34]   #0=67 1=89 2=34
arr=np.array([[23,45,67],[34,145,67],[67,89,34]])
print(arr[1,1])
print(arr[1,2])
print(arr[0,0])

145
67
23


In [49]:
#[[23,45,67],[34,145,67],[67,89,34],[23,45,167]]
#167
arr=np.array([[34,145,267,45,67,89,56],[34,145,267,45,67,89,56],[34,145,267,45,67,89,56],[34,145,267,45,67,89,56]])
#167
# print(arr[3,2])
#267
#[34,145,267,45,67,89,56]   
print(arr[1,1:5])  #row,colums

[145 267  45  67]


In [52]:
# 4 rows 5 colums in each row
z=np.array([[34,45,64,89,36],[22,69,23,67,89],[56,78,24,56,67],[34,67,89,23,47]])
print(z)
print(z[2,0:3]) 

[[34 45 64 89 36]
 [22 69 23 67 89]
 [56 78 24 56 67]
 [34 67 89 23 47]]
[56 78 24]


In [54]:
#22,69,23,67
print(z[1,0:4])

[22 69 23 67]


In [56]:
#break 
#continue

# 1 2 3 4 5,6,7
#while loops
x=1
while (x<8):
  print(x)
  if(x==3):
    break
  x=x+1


1
2
3


In [6]:
s=0
while (s<8):
  s=s+1
  if(s==3):
    continue
  print(s)
  
#12 4567

1
2
4
5
6
7
8


In [7]:
s=0
while (s<8):
  #s=s+1   #s=4
  if(s==3):
    continue  #3  if(s==3)
  print(s)
  s=s+1

0
1
2


KeyboardInterrupt: ignored

In [3]:
y=2
while(y<6):
  print(y)
  y=y+1

2
3
4
5


In [8]:
# 20 -30  #25
# 40 57 # 49
x=20
while(x<31):
  x=x+1
  if(x==25):
    continue
  print(x)

21
22
23
24
26
27
28
29
30
31


In [9]:
# 40 57 # 49  
x=39
while(x<57):
  x=x+1
  if(x==49):
    continue
  print(x)

40
41
42
43
44
45
46
47
48
50
51
52
53
54
55
56
57


In [10]:
#40 50  #even numbers   41,43,.........

x=39
while(x<50):  #39 ...........50
  x=x+1
  if(x%2==0):  #even  x==43  43
    continue
  print(x)

41
43
45
47
49


In [11]:
#23 33  #odd numbers 
x=22
while(x<33):
  x=x+1
  if(x%2!=0):
    continue
  print(x)

24
26
28
30
32


In [ ]:
# 23 30 >25   23,24....30  >25    26,27,28,29,30


In [ ]:
#23 to 30             23,24,25,26,27,28,29,30   #23 33 
#>25   26,27,28,29,30

In [12]:
x=23
while(x<=30):
  if(x>25):
    print(x)
  x=x+1


26
27
28
29
30


In [13]:
#20 40    <30 
#20,21,................29
x=20
while(x<=40):
  if(x<30): 
    print(x)
  x=x+1

20
21
22
23
24
25
26
27
28
29
